name: lint

on:
  push:
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: JohnnyMorganz/stylua-action@1.0.0
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            args: --check .
